import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const YOUTUBE_API_KEY = Deno.env.get("YOUTUBE_API_KEY") || "AIzaSyADeC0zLvPcZ_jnbTYG5qfWE-cKTwnO4_0";
const MEDIA_API_TOKEN = Deno.env.get("MEDIA_API_TOKEN") || "my-secret-token";

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

// ================== Utility Functions ==================

function generateJobId(prefix: string): string {
  const timestamp = Date.now().toString(36);
  const random = Math.random().toString(36).substring(2, 8);
  return `${prefix}_${timestamp}_${random}`;
}

function extractVideoId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/|youtube\.com\/v\/)([a-zA-Z0-9_-]{11})/,
    /youtube\.com\/shorts\/([a-zA-Z0-9_-]{11})/,
  ];
  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) return match[1];
  }
  return null;
}

function parseDuration(duration: string): number {
  const match = duration.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);
  if (!match) return 0;
  return parseInt(match[1] || "0") * 3600 + parseInt(match[2] || "0") * 60 + parseInt(match[3] || "0");
}

function formatVttTime(seconds: number): string {
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const ms = Math.floor((seconds % 1) * 1000);
  return `${hrs.toString().padStart(2, "0")}:${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}.${ms.toString().padStart(3, "0")}`;
}

async function computeSha256(text: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(text);
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(hashBuffer)).map(b => b.toString(16).padStart(2, "0")).join("");
}

// ================== YouTube Metadata ==================

async function getVideoMetadata(videoId: string): Promise<any> {
  const apiUrl = `https://www.googleapis.com/youtube/v3/videos?part=snippet,contentDetails&id=${videoId}&key=${YOUTUBE_API_KEY}`;

  const response = await fetch(apiUrl);
  if (!response.ok) throw new Error(`YouTube API error: ${response.status}`);

  const data = await response.json();
  if (!data.items || data.items.length === 0) throw new Error("Video not found");

  const item = data.items[0];
  return {
    id: videoId,
    title: item.snippet.title,
    original_title: item.snippet.title,
    description: item.snippet.description,
    channel_id: item.snippet.channelId,
    channel_name: item.snippet.channelTitle,
    published_at: item.snippet.publishedAt,
    duration_seconds: parseDuration(item.contentDetails.duration),
    thumbnail_url: item.snippet.thumbnails?.high?.url || item.snippet.thumbnails?.default?.url,
  };
}

// ================== Transcript Extraction ==================

async function getTranscriptFromFreeAPI(videoId: string, language: string = "en"): Promise<{ text: string; segments: any[]; source: string } | null> {
  try {
    // Use free YouTube transcript API
    const url = `https://youtube-transcript.ai/transcript/${videoId}.txt?lang=${language}`;
    const response = await fetch(url, { signal: AbortSignal.timeout(30000) });

    if (!response.ok) return null;

    const text = await response.text();

    // Parse the markdown transcript into segments
    const segments = parseMarkdownTranscript(text);

    if (segments.length > 0) {
      // Detect if auto-generated by checking the metadata
      const isAuto = text.includes("[auto]");
      return {
        text,
        segments,
        source: isAuto ? "auto_caption" : "official_caption"
      };
    }
  } catch (err) {
    console.error("Free transcript API error:", err);
  }
  return null;
}

function parseMarkdownTranscript(markdown: string): any[] {
  const segments: any[] = [];
  const lines = markdown.split('\n');

  let currentTime = 0;
  let currentText = "";
  let inTranscript = false;

  for (const line of lines) {
    // Skip header until we hit the transcript section
    if (line.startsWith("## Transcript")) {
      inTranscript = true;
      continue;
    }

    if (!inTranscript) continue;

    // Skip empty lines and divider
    if (!line.trim() || line.startsWith("---") || line.startsWith("Generated by")) continue;

    // Parse timestamp lines like "[0:01] text" or "[1:35] text"
    const timestampMatch = line.match(/\[(\d+):(\d+)(?::(\d+))?\]\s*(.+)/);
    if (timestampMatch) {
      // Save previous segment
      if (currentText) {
        segments.push({
          start: currentTime,
          end: currentTime + 5, // Estimate duration
          text: currentText.trim()
        });
      }

      // Parse new timestamp
      const mins = parseInt(timestampMatch[1], 10);
      const secs = parseInt(timestampMatch[2], 10);
      currentTime = mins * 60 + secs;
      currentText = timestampMatch[4] || "";
    } else if (line.trim()) {
      // Continuation of current text
      currentText += " " + line.trim();
    }
  }

  // Save last segment
  if (currentText) {
    segments.push({
      start: currentTime,
      end: currentTime + 5,
      text: currentText.trim()
    });
  }

  return segments;
}

function segmentsToVtt(segments: any[]): string {
  let vtt = "WEBVTT\n\n";
  for (let i = 0; i < segments.length; i++) {
    const seg = segments[i];
    vtt += `${i + 1}\n${formatVttTime(seg.start)} --> ${formatVttTime(seg.end)}\n${seg.text}\n\n`;
  }
  return vtt;
}

function segmentsToSrt(segments: any[]): string {
  let srt = "";
  for (let i = 0; i < segments.length; i++) {
    const seg = segments[i];
    const start = formatSrtTime(seg.start);
    const end = formatSrtTime(seg.end);
    srt += `${i + 1}\n${start} --> ${end}\n${seg.text}\n\n`;
  }
  return srt;
}

function formatSrtTime(seconds: number): string {
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const ms = Math.floor((seconds % 1) * 1000);
  return `${hrs.toString().padStart(2, "0")}:${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")},${ms.toString().padStart(3, "0")}`;
}

function calculateQualityMetrics(segments: any[], durationSeconds: number) {
  const text = segments.map(s => s.text).join(" ");
  const text_chars = text.length;
  const last_timestamp = segments.length > 0 ? segments[segments.length - 1].end : 0;
  const coverage_ratio = durationSeconds > 0 ? Math.min(last_timestamp / durationSeconds, 1) : 0;
  return {
    text_chars,
    last_timestamp_seconds: Math.floor(last_timestamp),
    coverage_ratio: Math.round(coverage_ratio * 10000) / 10000,
  };
}

function verifyToken(req: Request): boolean {
  const auth = req.headers.get("Authorization");
  if (!auth) return false;
  return auth.replace("Bearer ", "") === MEDIA_API_TOKEN;
}

// ================== Main Handler ==================

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  // Health check - no auth required
  if (req.url.includes("/health")) {
    return new Response(
      JSON.stringify({ status: "ok", service: "youtube-transcript-service", version: "3.0" }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }

  // Verify authorization
  if (!verifyToken(req)) {
    return new Response(
      JSON.stringify({ error: "Unauthorized", message: "Invalid or missing API token" }),
      { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }

  try {
    const url = new URL(req.url);

    // POST /media-extract
    if (req.method === "POST" && url.pathname.includes("/media-extract")) {
      const body = await req.json();
      const { url: videoUrl, language = "en" } = body;

      const videoId = extractVideoId(videoUrl);
      if (!videoId) {
        return new Response(
          JSON.stringify({ error: "Invalid URL", message: "Could not extract YouTube video ID" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const jobId = generateJobId("media");

      await supabase.from("jobs").insert({
        id: jobId,
        job_type: "media-extract",
        status: "queued",
        request_data: { url: videoUrl, video_id: videoId, language },
      });

      EdgeRuntime.waitUntil(processVideo(jobId, videoId, language));

      return new Response(
        JSON.stringify({ job_id: jobId, status: "queued" }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // GET /media-extract/{job_id}
    if (req.method === "GET" && url.pathname.includes("/media-extract")) {
      const pathParts = url.pathname.split("/").filter(p => p);
      const mediaIdx = pathParts.findIndex(p => p === "media-extract");

      if (mediaIdx === -1 || pathParts.length <= mediaIdx + 1) {
        return new Response(
          JSON.stringify({ error: "Not found", message: "Missing job ID" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const jobId = pathParts[mediaIdx + 1];
      const action = pathParts[mediaIdx + 2];

      if (!action) {
        const { data: job } = await supabase.from("jobs").select("*").eq("id", jobId).maybeSingle();

        if (!job) {
          return new Response(
            JSON.stringify({ error: "Not found", message: "Job not found" }),
            { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
          );
        }

        return new Response(JSON.stringify(job), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
      }

      // Download files
      if (action === "files" && pathParts.length > mediaIdx + 3) {
        const fileType = pathParts[mediaIdx + 3];

        const { data: job } = await supabase.from("jobs").select("result_data, status").eq("id", jobId).maybeSingle();

        if (!job || job.status !== "success") {
          return new Response(
            JSON.stringify({ error: "Not ready", message: "Job not complete" }),
            { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
          );
        }

        const result = job.result_data as any || {};

        switch (fileType) {
          case "transcript.txt":
            return new Response(result.transcript_text || "", { headers: { ...corsHeaders, "Content-Type": "text/plain; charset=utf-8" } });
          case "transcript.vtt":
            return new Response(result.transcript_vtt || "", { headers: { ...corsHeaders, "Content-Type": "text/vtt; charset=utf-8" } });
          case "transcript.srt":
            return new Response(result.transcript_srt || "", { headers: { ...corsHeaders, "Content-Type": "text/plain; charset=utf-8" } });
          default:
            return new Response(JSON.stringify(result, null, 2), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
        }
      }
    }

    return new Response(
      JSON.stringify({ error: "Not found", message: "Endpoint not found" }),
      { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );

  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : "Unknown error";
    return new Response(
      JSON.stringify({ error: "Internal error", message: errorMessage }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});

// ================== Background Processing ==================

async function processVideo(jobId: string, videoId: string, language: string) {
  try {
    await supabase.from("jobs").update({ status: "running", started_at: new Date().toISOString() }).eq("id", jobId);

    console.log(`Processing ${videoId}`);

    // Get metadata
    const metadata = await getVideoMetadata(videoId);
    console.log(`Got metadata: ${metadata.title}`);

    await supabase.from("videos").upsert({
      id: videoId,
      title: metadata.title,
      original_title: metadata.original_title,
      description: metadata.description,
      channel_id: metadata.channel_id,
      channel_name: metadata.channel_name,
      published_at: metadata.published_at,
      duration_seconds: metadata.duration_seconds,
      thumbnail_url: metadata.thumbnail_url,
      updated_at: new Date().toISOString(),
    });

    // Get transcript using free API
    const result = await getTranscriptFromFreeAPI(videoId, language);

    if (result && result.segments.length > 0) {
      console.log(`Got ${result.segments.length} segments via ${result.source}`);

      const txtContent = result.segments.map(s => s.text).join("\n");
      const vttContent = segmentsToVtt(result.segments);
      const srtContent = segmentsToSrt(result.segments);
      const metrics = calculateQualityMetrics(result.segments, metadata.duration_seconds);
      const sha256 = await computeSha256(txtContent);

      await supabase.from("transcripts").upsert({
        video_id: videoId,
        source: result.source,
        language,
        text_chars: metrics.text_chars,
        sha256,
        duration_seconds: metadata.duration_seconds,
        last_timestamp_seconds: metrics.last_timestamp_seconds,
        coverage_ratio: metrics.coverage_ratio,
        has_vtt: true,
        has_srt: true,
      });

      await supabase.from("jobs").update({
        status: "success",
        completed_at: new Date().toISOString(),
        result_data: {
          video_id: videoId,
          title: metadata.title,
          duration_seconds: metadata.duration_seconds,
          transcript_source: result.source,
          transcript_text: txtContent,
          transcript_vtt: vttContent,
          transcript_srt: srtContent,
          full_transcript: result.text, // Original markdown from API
          text_chars: metrics.text_chars,
          sha256,
          last_timestamp_seconds: metrics.last_timestamp_seconds,
          coverage_ratio: metrics.coverage_ratio,
          segments_count: result.segments.length,
        },
      }).eq("id", jobId);

      console.log(`Job ${jobId} success: ${metrics.text_chars} chars`);
    } else {
      await supabase.from("jobs").update({
        status: "failed",
        completed_at: new Date().toISOString(),
        error_type: "no_transcript",
        error_message: "No captions available for this video",
      }).eq("id", jobId);

      console.log(`Job ${jobId} failed: no captions`);
    }
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : "Unknown";
    console.error(`Job ${jobId} error:`, errorMessage);

    await supabase.from("jobs").update({
      status: "failed",
      completed_at: new Date().toISOString(),
      error_type: "processing_error",
      error_message: errorMessage,
    }).eq("id", jobId);
  }
}
